name: "re_data_integration_tests"
version: "1.0"
config-version: 2

# Changed when running tests
profile: "re_data_postgres"

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

models:
  re_data:
    enabled: true

sources:
  re_data_integration_tests:
    +re_data_monitored: true
    +re_data_time_filter: null
  
vars:
  re_data:anomaly_detector:
    name: modified_z_score
    threshold: 0.6
  re_data:max_columns_in_query: 1

  re_data:metrics_base:
    table:
      - row_count
      - freshness
      - my_distinct_table_rows

    column:
      numeric:
        - min
        - max
        - avg
        - stddev
        - variance
        - nulls_count
        - nulls_percent
        - diff # my own custom metric

      text:
        - min_length
        - max_length
        - avg_length
        - nulls_count
        - nulls_percent
        - missing_percent
        - missing_count

seeds:
  +schema: seeds
  +quote_columns: false

  re_data_integration_tests:
    monitoring:
      sample_with_anomaly:
        +re_data_monitored: true
        +re_data_time_filter: creation_time

      sample_without_time_filter:
        +re_data_monitored: true
        +re_data_time_filter: null

      sample_table:
        +re_data_monitored: true
        +re_data_time_filter: creation_time
        
        +re_data_columns: 
          - event_type
          - value1
          - value2
          - null_value
        
        +re_data_metrics:
          table:
            - my_custom_table_metric # my own custom metric
            - distinct_table_rows
          column:
            event_type:
              - regex_test:
                  regex: ([A-Za-z0-9]+)
              - match_regex:
                  regex: ^sell
              - match_regex_percent:
                  regex: ^sell
              - not_match_regex:
                  regex: ^buy
              - not_match_regex_percent:
                  regex: ^buy
              - distinct_values
              - duplicate_values
              - duplicate_rows
              - unique_rows

      expected_z_score:
        +column_types:
          time_window_end: "TIMESTAMP"

      expected_metrics:
        +column_types:
          time_window_start: "TIMESTAMP"
          time_window_end: "TIMESTAMP"
